spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  cache:
    redis:
      defaultExpireTime : 0
      expireTime:
        billDetailData : 3600
        billSummaryInfos : 3600